To visualize npz file

Data Loader

In [1]:
import json
import numpy as np
from pathlib import Path


In [9]:

repo_root = Path.cwd().parent

processed_root = repo_root / "data" / "ecg" / "processed" / "v2" 

t = "train"

label_data = np.load(processed_root / t / "labels" / "label_shard_000.npz")
td_data = np.load(processed_root / t / "time_domain_data" / "td_shard_000.npz")
fd_data = np.load(processed_root / t / "frequency_domain_data" / "fd_shard_000.npz")

frequency_bins = np.load(processed_root / "frequency_bins.npz")["data"]

with open(processed_root / "label_map.json", "r") as f:
    label_map = json.load(f)

Print Keys

In [10]:
print("label keys:", label_data.files)
print("td keys:", td_data.files)
print("fd keys:", fd_data.files)

label keys: ['data']
td keys: ['data']
fd keys: ['data']


Inspect shapes and dtypes

In [11]:
for name, data in [("label", label_data), ("td", td_data), ("fd", fd_data)]:
    print(f"\n{name.upper()}")
    for key in data.files:
        arr = data[key]
        print(f"{key}: shape={arr.shape}, dtype={arr.dtype}")


LABEL
data: shape=(6750,), dtype=int64

TD
data: shape=(6750, 2, 361), dtype=float32

FD
data: shape=(6750, 2, 181, 2), dtype=float32


To verify the stored content

In [12]:
label_arr = label_data["data"]
td_arr = td_data["data"]
fd_arr = fd_data["data"]

print("label_map:", label_map)
print("frequency_bins shape:", frequency_bins.shape)

print("\nFirst 10 labels:")
print(label_arr[:10])

print("\nOne TD sample shape:", td_arr[0].shape)
print("One FD sample shape:", fd_arr[0].shape)

print("\nTD sample 0, channel 0, first 10 values:")
print(td_arr[0, 0, :10])

print("\nFD sample 0, channel 0, first 5 frequency bins [magnitude, phase]:")
print(fd_arr[0, 0, :5, :])

label_map: {'N': 0, 'S': 1, 'V': 2}
frequency_bins shape: (181,)

First 10 labels:
[0 0 0 0 0 0 0 0 0 0]

One TD sample shape: (2, 361)
One FD sample shape: (2, 181, 2)

TD sample 0, channel 0, first 10 values:
[-0.355 -0.345 -0.345 -0.325 -0.305 -0.275 -0.27  -0.28  -0.29  -0.285]

FD sample 0, channel 0, first 5 frequency bins [magnitude, phase]:
[[ 2.3573637e-05  3.1415927e+00]
 [ 2.0431816e+01 -1.9144965e+00]
 [ 2.6228012e+01  6.2023306e-01]
 [ 1.8636873e+01  3.0397091e+00]
 [ 1.1413544e+01  5.2978009e-01]]


Frequency Bin Inspection

In [13]:
print("Frequency bins shape:", frequency_bins.shape)
print("Frequency resolution (Hz):", frequency_bins[1] - frequency_bins[0])

print("\nFirst 10 frequency bins (Hz):")
print(frequency_bins[:10])

print("\nLast 10 frequency bins (Hz):")
print(frequency_bins[-10:])

print("\nMin / Max frequency (Hz):")
print(frequency_bins[0], frequency_bins[-1])

Frequency bins shape: (181,)
Frequency resolution (Hz): 0.997229916897507

First 10 frequency bins (Hz):
[0.         0.99722992 1.99445983 2.99168975 3.98891967 4.98614958
 5.9833795  6.98060942 7.97783934 8.97506925]

Last 10 frequency bins (Hz):
[170.52631579 171.52354571 172.52077562 173.51800554 174.51523546
 175.51246537 176.50969529 177.50692521 178.50415512 179.50138504]

Min / Max frequency (Hz):
0.0 179.50138504155126


Label Map Inspection

In [14]:
unique_labels, counts = np.unique(label_arr, return_counts=True)

inv_label_map = {v: k for k, v in label_map.items()}

print("Label distribution:")
for label_id, count in zip(unique_labels, counts):
    print(f"{label_id:2d}  {inv_label_map[label_id]:>2s}  {count}")

Label distribution:
 0   N  2250
 1   S  2250
 2   V  2250
